apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-of-the-day
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-of-the-day
  template:
    metadata:
      labels:
        app: quote-of-the-day
    spec:
      containers:
      - name: quote-of-the-day
        image: ghcr.io/joveto1/quote-of-the-day:latest
        ports:
        - containerPort: 3000
