name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: joveto1/devops-framework/.github/workflows/node-build.yml@main

  docker:
    uses: joveto1/devops-framework/.github/workflows/docker-build-push.yml@main
    needs: build
    with:
      image-name: quote-of-the-day
